#output: matrix.o exceptions.o
#	g++ matrix.o exceptions.o -o output
#
#matrix.o: matrix.hpp
#	g++ -c matrix.cpp
#
#.PHONY: clean
#clean:
#	-rm output matrix.o exceptions.o

#output: test_matrix.o
#	g++ test_matrix.o -o output
#
#test_matrix.o: test_matrix.cpp
#	g++ -c test_matrix.cpp